### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by farfromrefug** [tentone/geo-three#10]
Would you be open to migrating the lib to typescript?
I am on my way to do it in my fork but want to ask you first. Cause merging will get very hard if one is in JS and the other in TS

**Comment by tentone** [comment]
Hello

Yes, I im planning to move this lib to TS. If you want to open a PR intiializing that convertion go ahead please.

Thanks a lot for your help.

**Comment by tentone** [comment]
@farfromrefug 

I have merged the typescript version to the master branch please take a look and see if it fits your needs.

Thanks a lot for the help!
