### ISSUE TITLE
3D terrain not woking with safari in macos

### ISSUE THREAD

**Issue by xawill** [tentone/geo-three#16]
Hi, and thank you for this library which looks awesome!

I am just not sure from the readme whether the library supports the generation of a 3D terrain. Because from what I read, it is possible to provide a height map tileset, but I haven't been able to reproduce any 3D terrain in the demo. It is always a planar map.

Did I miss something ?

I am looking for something similar to [Map33](https://github.com/blaze33/map33.js), but I prefer your coding style, focused on maintainability and of course written in TypeScript :)

Thank you!

**Comment by tentone** [comment]
Hello

The library supports 3D terrain tiles it is the main focus in this library.

You can open the example of the library and switch between modes and tile providers to experiment the multiple configurations.

Thanks a lot!

**Comment by xawill** [comment]
Thank you for your reply.

I think the issue is with the demo at [https://tentone.github.io/geo-three](https://tentone.github.io/geo-three). Try to load the page and check the console. A lot of "Failed to load height node data" errors display. I guess that we cannot test the 3D part of your library on the demo website due to this.

But most likely the issue is due to an error in authentication with MapBox height tiles server or something on the demo. I'll give it a try locally with my own tiles providers. Pretty sure it will work :)

**Comment by tentone** [comment]
The demo is not broken it is working correctly. These errors are caused by missing tiles for ocean regions and can be ignored.

![image](https://user-images.githubusercontent.com/9158354/122016739-382c4000-cdb9-11eb-8a62-46369fafb71a.png)

**Comment by xawill** [comment]
Well, it doesn't work for me, over Switzerland, a very mountainous country in the Alps in Europe.

I am using Safari latest public version on macOS latest public version.

<img width="1656" alt="Capture d’écran 2021-06-15 à 10 11 39" src="https://user-images.githubusercontent.com/2658206/122017249-16838680-cdc2-11eb-84e4-0a88f18f80da.png">

**Comment by xawill** [comment]
This is over Mont-Blanc (4809m):
<img width="1655" alt="Capture d’écran 2021-06-15 à 10 18 43" src="https://user-images.githubusercontent.com/2658206/122018393-1afc6f00-cdc3-11eb-9272-25ec82262e5f.png">

**Comment by tentone** [comment]
Can you please provide a height "not shader" screenshot of these areas?

I have no way of testing with mac os, do you have any shader related error?

**Comment by xawill** [comment]
No problem. I might be able to test on my side on Windows to try to narrow down what the issue is.

Here is the screenshot you requested: Mont-Blanc area again, with height "not shader". You can also see the output of the console, which is filled with hundred of such errors (one per tile, I would guess). I have no other error (no shader issue reported).

<img width="1674" alt="Capture d’écran 2021-06-15 à 14 23 36" src="https://user-images.githubusercontent.com/2658206/122051962-73dcff00-cde5-11eb-8598-7f0608b6d576.png">

PS: After writing this, I tested on Chrome on macOS and it works as expected (except from the gap at tiles edges, but I guess this is a complicated issue to solve for you, right ?):

<img width="1605" alt="Capture d’écran 2021-06-15 à 14 27 13" src="https://user-images.githubusercontent.com/2658206/122052479-08476180-cde6-11eb-827d-1608491b5afc.png">

So apparently the issue is with Safari on macOS exclusively.

**Comment by tentone** [comment]
Thanks a lot for this information this has to be fixed. The errors you're getting should not be related but i have to take a closer look maybe using a VM i can reproduce the error.

Thanks!

**Comment by xawill** [comment]
Thanks a lot. I didn't have the chance to integrate your library in my project yet, but will in the following hours/days. I will then have more extensive access to the debugger and will let you know if I can better identify the issue.

I thought at first that the issue might be related to Safari not supporting webgl2, but I don't think you use it. And I had Safari webgl2 experimental feature enabled.

**Comment by JannikGM** [comment]
I also have this issue on macOS running Firefox 89.0 (64-bit); so this isn't exclusive to Safari.

**Comment by xawill** [comment]
I didn't investigate at all, but I saw you use `OffscreenCanvas` a lot. This is still considered an experimental feature, is not supported by Safari and only partially by Firefox : https://developer.mozilla.org/fr/docs/Web/API/OffscreenCanvas.

**Comment by tentone** [comment]
@xawill That could be the reason for the height data to be missing.

I will patch the lib to use regular canvas object whenever  OffscreenCanvas is not available.

**Comment by tentone** [comment]
Removed the need for OffscreenCanvas in new version. Should be working correctly in safari now!

Thanks a lot!

**Comment by laraduarte** [comment]
Hi @tentone it's not working on my ipad, maybe we need to reopen this!
thank you

**Comment by tentone** [comment]
Hello @laraduarte please open a new issue regarding this problem.

Include the version of the browser and OS that youre running and any content from the console please.

Thanks a lot!

**Comment by laraduarte** [comment]
Hello @tentone 

System: Ipad, iOS 15.6
Browser: Google Chrome
No errors in the console.

Thank you!
