### ISSUE TITLE
demo link broken

### ISSUE THREAD

**Issue by wallabyway** [tentone/geo-three#17]
Currently live demo says...

"You can test the live demo of the library running from the GitHub page"
and points to https://tentone.github.io/geo-three/examples/index.html

It should point to:  https://tentone.github.io/geo-three/

**Comment by JannikGM** [comment]
Yes, but even if fixed, it's affected by https://github.com/tentone/geo-three/issues/16#issuecomment-860561933
While these 2 issues need to be fixed independently, they interact, because there's no benefit in linking a broken demo either (whether it's 404 or nonfunctional due to errors).

**Comment by tentone** [comment]
@wallabyway  Thanks a lot, i will fix the link and point it to the right URL.

**Comment by wallabyway** [comment]
Thank you for such an impressive library !

I back-ported it to an old Three.js R71 library
