### ISSUE TITLE
Types not published on npm ?

### ISSUE THREAD

**Issue by xawill** [tentone/geo-three#18]
While trying to add the library to my app, I noticed that the npm package only contains javascript code and no typings. Is it intentional ? Do you plan to publish the types as well ? We definitely both see the benefits of coding the library in typescript, but this is also useful to use it in typescript.

Thanks a lot!

**Comment by xawill** [comment]
Based on [this](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package), it looks like the only think you have to do is to set `declaration` to `true` here:

https://github.com/tentone/geo-three/blob/b6aebacee7bee3249821caf0eac7f14a355d383b/tsconfig.json#L11

Thanks again for the library !

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this issue.
 
I have enabled the type declarations that will be published to npm on next release today.

Cheers

**Comment by christjt** [comment]
This issue is fixed and can be closed once a new released is published.

**Comment by tentone** [comment]
Hello

Types are now published into NPM.

Thanks a lot!

Cheers
