### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by farfromrefug** [tentone/geo-three#3]
I would like to test your project but the example wont run.
Neither on your website nor when locally cloned.
```
Uncaught TypeError: Class constructor Wn cannot be invoked without 'new'
    at MapHeightNodeShader.MapHeightNode [as constructor] (geo-three.js:794)
    at new MapHeightNodeShader (geo-three.js:1339)
    at new MapView (geo-three.js:1699)
    at (index):143
    ```

**Comment by tentone** [comment]
Hello

Thanks a lot for reporting this issue, it is caused by changed in three.js library.

I will update the library code to be compliant with recent version of three.js

Cheers

**Comment by tentone** [comment]
A  new version 0.0.7 is now available that should be working correctly
