### ISSUE TITLE
google maps

### ISSUE THREAD

**Issue by PerspectivesLab** [tentone/geo-three#32]
Hi there, is the google maps provider listed in the example ( satellite + elevation ) ?
how can we use it ?
thank you

**Comment by tentone** [comment]
Hello

For google maps you will need access to tiles in the google maps API  wich requires a special type of developer key.

https://developers.google.com/maps/documentation/tile/overview#tile_requests

Cheers

**Comment by PerspectivesLab** [comment]
okay i will try that ! thx
