### ISSUE TITLE
when the layer  >15 terrian  render fbs will  be too low

### ISSUE THREAD

**Issue by fzw2408** [tentone/geo-three#35]
hi tentone ：
      here is a great project ：https://github.com/felixpalmer/procedural-gl-js ，the same GPU render terrian  his most smooth。but it cant add three object where you like、
       some suggestions：
        1 geo-three cluld add a tiledate buffer 。
        2 compatible the nasa.xyz's height image   
        3.reduce the tiledate request 
     geo-three will be more greate project 。

**Comment by fzw2408** [comment]
hi tentone ：
        here is my suggestions: it  clude Improve GPU operation speed and make GPU render terrian  his most smooth。
         float _height = ((_theight.r * 255.0 * 65536.0 + _theight.g * 255.0 * 256.0 + _theight.b * 255.0) * 0.1) - 10000.0;
        NASA.xyz
	 **float _height = (_theight.r * 256 + _theight.g ) - 32768.0;** 
       个人观点：
        procedural-gl    世界观和格局 太小，想加点three obj 十分吃力。
        geo-three         世界观和格局刚刚好，但是球面模式似乎还没完善。很期待 Geo.MapView.SPHERICAL。

**Comment by tentone** [comment]
Hello

Thanks a lot for the suggestions.

I will take a look in these.

Cheers
