### ISSUE TITLE
Types not working again?

### ISSUE THREAD

**Issue by mysterybear** [tentone/geo-three#39]
Hi

I see there was #18 and #19 

I've just done like

```
yarn create react-app --template typescript try-geo-three
yarn add geo-three
```

And then try to `import * as foo from "geo-three"` and I'm getting:

```
error TS7016: Could not find a declaration file for module 'geo-three'. '/home/tom/dev/now/try-geo-three/node_modules/geo-three/build/geo-three.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/geo-three` if it exists or add a new declaration (.d.ts) file containing `declare module 'geo-three';`

4 import * as foo from "geo-three"
                       ~~~~~~~~~~~
Found 1 error in src/App.tsx:4
```

This is with 0.1.0

**Comment by tentone** [comment]
Hello

I will have to recheck this topic i have been using the library  with typescript without any issue.

![image](https://user-images.githubusercontent.com/9158354/176901501-3dc2a791-ddc8-4b8d-84ce-5942a3ccec9a.png)

Can you please provide your transpiler settings?

**Comment by anhle1476** [comment]
@tentone thank you. It works for me 😁

**Comment by tentone** [comment]
Great! Thanks a lot!
