### ISSUE TITLE
How to load tiles with a resolution of 512 * 512 or 1024 * 1024？

### ISSUE THREAD

**Issue by wuzhenzhen1314** [tentone/geo-three#50]
Hi, first of all, Great Project here! Thank you !
I want to ask a question：how to load tiles with a resolution of 512 * 512 or 1024 * 1024？
Tiles are generated through geoserver service，and large resolution tiles are loaded to reduce the number of requests
Look forward to your reply，thanks in advance.

**Comment by tentone** [comment]
Hello

There should be no limitation regarding the tile size. Did you have any trouble loading higher size textures?

Thanks in advance.
