### ISSUE TITLE
map installed by npm and map run in example have different colors

### ISSUE THREAD

**Issue by clearisoft** [tentone/geo-three#67]
![3](https://github.com/tentone/geo-three/assets/34474097/87ec5223-3193-492c-93eb-044b51d71229)

I do not known why?  :(

**Comment by tentone** [comment]
Hello

These are probably using different providers.

The provider will indicate the source of the map tiles (mapbox, google maps, etc)

**Comment by clearisoft** [comment]
I have carefully examined the examples in the example and my program, and noticed that the URLs of the images referenced in the tiles are exactly the same. However, when rendered, the visuals in my program appear brighter, as if there is lighting in the scene. In reality, there is no lighting in the scene.

**Comment by tentone** [comment]
The example has lights set, so thats might be the difference

**Comment by clearisoft** [comment]
I fix it，it is a bug of three.js after 0.152.0

**Comment by tobias74** [comment]
I have the same problem. Reverting to 0.151.3 of three.js solved the issue. My question now would be: Is this really a bug in three.js, or rather some sort of incompatibility that could be resolved otherwise? For me reverting to 1.151.3 of three.js is not possible because it introduces lighting and contrast problems in other areas of my project...

**Comment by tentone** [comment]
This might be caused by the changes in color management in three.js

I will update the project to use the latest version and test to ensure that colors are kept as they were.

**Comment by tentone** [comment]
A simple to get around would be to disable color management in project, but its not the correct way to go about it.

![image](https://github.com/tentone/geo-three/assets/9158354/bf64c026-682a-4d59-9965-c99b72578cb2)

I will update all color usage in the project to be as close as possible to the old model, but it is expect to have some differences in the end result.
