### ISSUE TITLE
Texture marked for update but no image data found.

### ISSUE THREAD

**Issue by VivekSri006** [tentone/geo-three#70]
![image](https://github.com/tentone/geo-three/assets/88841892/bdf37310-4600-4c68-92c0-6fb4e127a90e)

i uploaded tiles of selected area then i'm getting this warning :Texture marked for update but no image data found.

**Comment by tentone** [comment]
Hello

Sorry for the extremely late response, this might be caused by bad URL on image,

can you provide an example?
