### ISSUE TITLE
your live demos have some error, it's not work well.

### ISSUE THREAD

**Issue by FengFengmomo** [tentone/geo-three#73]
and when i use sphere, it doesnt show right tile when i zoom in and out! mesh doesn't show childs

**Comment by FengFengmomo** [comment]
when it zoom to level 4, it doesn't continue to zoom in.
i use LODFrustum

**Comment by tentone** [comment]
Hello

Currently the sphere demo is a bit limited, since the existing tiles dont fit the model correctly i have put much effort.

But still if you want to you can adjust the lod sensitivity wich should make them load faster and get to full detail.
