### ISSUE TITLE
Could not find a declaration file for module 'geo-three'

### ISSUE THREAD

**Issue by RodrigoHamuy** [tentone/geo-three#81]
Typescript projects get a "Could not find a declaration file for module 'geo-three'." error.

Steps to reproduce:

1. Start a new `vite` project using `npm create vite@latest`.
2. Make sure project uses `react` and `typescript`.
3. Install `geo-three`.
4. Add `import { MapView } from "geo-three";` in `src/main.tsx`.

You will get the following Typescript error:

> Could not find a declaration file for module 'geo-three'. './node_modules/geo-three/build/geo-three.module.js' implicitly has an 'any' type.\n  There are types at './node_modules/geo-three/build/Main.d.ts', but this result could not be resolved when respecting package.json \"exports\". The 'geo-three' library may need to update its package.json or typings.

**Comment by shot-codes** [comment]
I experience this issue in sveltekit.
